# Generated by Django 3.2.5 on 2022-06-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_id',
            fields=[
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=18)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_infomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.CharField(max_length=16)),
                ('sex', models.CharField(max_length=16)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_id')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('body', models.CharField(max_length=130072)),
                ('date', models.DateTimeField(auto_now=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_id')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('msg', models.CharField(max_length=65536)),
                ('uid_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid_receive', to='main.user_id')),
                ('uid_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid_send', to='main.user_id')),
            ],
        ),
        migrations.CreateModel(
            name='follow_list',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False)),
                ('be_followed_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_followed_uid', to='main.user_id')),
                ('follow_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_uid', to='main.user_id')),
            ],
        ),
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_id')),
            ],
        ),
        migrations.CreateModel(
            name='back_post',
            fields=[
                ('back_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=65536)),
                ('date', models.DateTimeField(auto_now=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_id')),
            ],
        ),
    ]
